### ISSUE TITLE
Added configuration for rendering root

### ISSUE THREAD

**Issue by alex3683** [aixigo/pdfreactor-loader#5]
Add configuration for the assets root of the http server.

**Comment by alex3683** [comment]
Hack implemented on this branch: `feature/5-add-context-configuration`

**Comment by jpommerening** [comment]
Regarding the configurable location to resolve assets… the `css-loader` has a similar option and they are calling it `root`: https://github.com/webpack-contrib/css-loader#options

**Comment by jpommerening** [comment]
Fixed via #5

Implemented on `master` (`v0.3.0`)
